services:
  postgres-db:
    image: postgres:15
    container_name: chitchiat-db
    restart: always
    environment:
      POSTGRES_USER: chitchiat-user
      POSTGRES_PASSWORD: chitchiat-password
      POSTGRES_DB: chitchiat-app-db
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
